--- b/pintraces/Makefile	2012-11-29 04:26:26.000000000 +0100
+++ a/pintraces/Makefile	2016-09-09 11:48:47.943981217 +0200
@@ -50,7 +50,7 @@
 
 ifeq ($(TARGET_COMPILER),gnu)
     include $(PIN_HOME)/source/tools/makefile.gnu.config
-    CXXFLAGS ?= -Wall -Werror -Wno-unknown-pragmas $(DBG) $(OPT)
+    CXXFLAGS ?= -Wall -Wno-unknown-pragmas $(DBG) $(OPT)
     PIN=$(PIN_HOME)/pin
 	RM = rm -rf
 endif
@@ -69,7 +69,7 @@
 ##############################################################
 
 
-TOOL_ROOTS = gentrace #ctxtest
+TOOL_ROOTS = gentrace
 
 TOOLS = $(TOOL_ROOTS:%=$(OBJDIR)%$(PINTOOL_SUFFIX))
 
@@ -111,7 +111,7 @@
 	-mkdir "$(OBJDIR)"
 
 #$(OBJDIR)gentrace.o : gentrace.cpp 
-#	$(CXX) -c $(CXXFLAGS) $(PIN_CXXFLAGS) ${OUTOPT}$@ $<
+#	$(CXX) -c $(CXXFLAGS) -std=c++0x $(PIN_CXXFLAGS) ${OUTOPT}$@ $<
 
 #$(OBJDIR)pivot.o : pivot.cpp
 #	$(CXX) -c $(CXXFLAGS) $(PIN_CXXFLAGS) ${OUTOPT}$@ $<
@@ -129,10 +129,10 @@
 #	$(CXX) -c $(CXXFLAGS) $(PIN_CXXFLAGS) ${OUTOPT}$@ $<
 
 $(OBJDIR)%.o : $(TRACEDIR)/%.cpp
-	$(CXX) -c $(CXXFLAGS) $(PIN_CXXFLAGS) ${OUTOPT}$@ $<
+	$(CXX) -c $(CXXFLAGS) -std=c++0x $(PIN_CXXFLAGS) ${OUTOPT}$@ $<
 
 $(OBJDIR)%.o : %.cpp
-	$(CXX) -c $(CXXFLAGS) $(PIN_CXXFLAGS) ${OUTOPT}$@ $<
+	$(CXX) -c $(CXXFLAGS) -std=c++0x $(PIN_CXXFLAGS) ${OUTOPT}$@ $<
 
 $(OBJDIR)%.o : $(TRACEFORMATPBDIR)/%.cc
 	$(CXX) -c $(CXXFLAGS) $(PIN_CXXFLAGS) ${OUTOPT}$@ $<
