/*
    Open Security Analysis Workbench (OpenSAW) - A concolic security test tool
    Copyright (C) 2016 Ericsson AB

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; version 2 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/
//Automatically generated by mazes.py
#include <iostream>
#include <fstream>

int MAZE_WIDTH=5;
int MAZE_HEIGHT=5;

int main(int argc, char* argv[]) {
  char* inFile;
  if (argc != 2) {
    std::cerr << "Usage is <infile>\n";
    return 1;
  }
  else {
    inFile = argv[1];
  }

  int i = 1;
  int j = 1;
  char c;
  char pc = ' ';
  std::ifstream is(inFile);
  if (!is.is_open()) {
    std::cerr << "Unable to open input file\n";
    return 1;
  }

  while(!is.eof()) {
    if (i == MAZE_WIDTH && j == MAZE_HEIGHT) {
      std::cout << "Done." << std::endl;
      break;
    }
    c = is.get();
    if (!(c == 'U' || c == 'D' || c == 'L' || c == 'R') ||
        (pc == 'U' && c == 'D') || (pc == 'L' && c == 'R') ||
        (pc == 'D' && c == 'U') || (pc == 'R' && c == 'L')) {
      std::cout << "Illegal move!" << std::endl;
      break;
    }
    pc = c;
    if (i == 1 && j == 1) {
      if (c == 'R') {j++;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 1 && j == 2) {
      if (c == 'R') {j++;}
      else if (c == 'L') {j--;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 1 && j == 3) {
      if (c == 'L') {j--;}
      else if (c == 'R') {j++;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 1 && j == 4) {
      if (c == 'L') {j--;}
      else if (c == 'D') {i++;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 1 && j == 5) {
      if (c == 'D') {i++;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 2 && j == 1) {
      if (c == 'D') {i++;}
      else if (c == 'R') {j++;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 2 && j == 2) {
      if (c == 'D') {i++;}
      else if (c == 'L') {j--;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 2 && j == 3) {
      if (c == 'R') {j++;}
      else if (c == 'D') {i++;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 2 && j == 4) {
      if (c == 'L') {j--;}
      else if (c == 'U') {i--;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 2 && j == 5) {
      if (c == 'U') {i--;}
      else if (c == 'D') {i++;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 3 && j == 1) {
      if (c == 'D') {i++;}
      else if (c == 'U') {i--;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 3 && j == 2) {
      if (c == 'U') {i--;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 3 && j == 3) {
      if (c == 'U') {i--;}
      else if (c == 'D') {i++;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 3 && j == 4) {
      if (c == 'D') {i++;}
      else if (c == 'R') {j++;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 3 && j == 5) {
      if (c == 'D') {i++;}
      else if (c == 'U') {i--;}
      else if (c == 'L') {j--;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 4 && j == 1) {
      if (c == 'D') {i++;}
      else if (c == 'U') {i--;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 4 && j == 2) {
      if (c == 'D') {i++;}
      else if (c == 'R') {j++;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 4 && j == 3) {
      if (c == 'L') {j--;}
      else if (c == 'U') {i--;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 4 && j == 4) {
      if (c == 'D') {i++;}
      else if (c == 'U') {i--;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 4 && j == 5) {
      if (c == 'U') {i--;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 5 && j == 1) {
      if (c == 'U') {i--;}
      else if (c == 'R') {j++;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 5 && j == 2) {
      if (c == 'L') {j--;}
      else if (c == 'U') {i--;}
      else if (c == 'R') {j++;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 5 && j == 3) {
      if (c == 'R') {j++;}
      else if (c == 'L') {j--;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 5 && j == 4) {
      if (c == 'U') {i--;}
      else if (c == 'R') {j++;}
      else if (c == 'L') {j--;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
    if (i == 5 && j == 5) {
      if (c == 'L') {j--;}
      else {
        std::cout << "Illegal move!" << std::endl;
        break;
      }
      continue;
    }
  }
  is.close();
  std::cout << "Position: " << i << ", " << j << std::endl;
  return 0;
}
